linters-settings:
  custom:
    vinego:
      type: "module"
      settings:
        enable_varinit: true
        enable_explicitcast: true
        enable_capturederr: true
linters:
  enable:
    - vinego
