name: ci
on:
  push:
    tags:
      - "v*"
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - id: dockermeta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/platformsh/vinego
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PUBLISH_DEVREL }}
      - uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src"
          push: true
          tags: ${{ steps.dockermeta.outputs.tags }}
